#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config external_bar              all:40:0
yabai -m config auto_balance              on
yabai -m config window_zoom_persist       on
yabai -m config window_animation_duration 0.05
yabai -m config window_animation_easing   easeInOutQuint

# Set all padding (default: 0)
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

# modify window shadows (default: on, options: on, off, float)
yabai -m config window_shadow float

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# center mouse on window with focus
yabai -m config mouse_follows_focus off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier cmd
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action stack

# disable specific apps
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^VLC$" manage=off
yabai -m rule --add app="^Little Snitch Software Update$" manage=off
yabai -m rule --add app="^iStat Menus$" manage=off
yabai -m rule --add app="^Raycast" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off

echo "yabai configuration loaded.."

