#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# default layout (can be bsp, stack or float)
yabai -m config layout bsp
yabai -m config external_bar all:40:0
yabai -m config auto_balance on

# Set all padding (default: 0)
yabai -m config top_padding    9
yabai -m config bottom_padding 9
yabai -m config left_padding   9
yabai -m config right_padding  9
yabai -m config window_gap     15

# modify window shadows (default: on, options: on, off, float)
yabai -m config window_shadow float
yabai -m config window_zoom_persist on
yabai -m config window_animation_duration 0.1
yabai -m config window_animation_easing easeInOutQuint
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.05
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.83
# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# center mouse on window with focus
yabai -m config mouse_follows_focus off
# focus window under cursor
yabai -m config focus_follows_mouse off
# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action stack

# disable specific apps
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" title="New Message" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Obsidian" app="^Obsidian$" title="^Obsidian$" manage=off
yabai -m rule --add label="VLC" app="^VLC$" manage=off
yabai -m rule --add label="Little Snitch Software Update" app="^Little Snitch Software Update$" manage=off
yabai -m rule --add label="iStat Menus" app="^iStat Menus$" manage=off
yabai -m rule --add label="Raycast" app="^Raycast" manage=off
yabai -m rule --add label="Karabiner-Elements" app="^Karabiner-Elements$" manage=off

# configure spaces
yabai -m space 1 --label "com"
yabai -m rule --add app="Mail" title!="New Message" space=^1
yabai -m rule --add app="Telegram" space=^1

yabai -m space 2 --label "copium"
yabai -m rule --add app="Fork" space=^2
yabai -m rule --add app="Obsidian" space=^2

yabai -m space 3 --label "web"
yabai -m rule --add app="Safari" space=^3
yabai -m rule --add app="Brave" space=^3
yabai -m rule --add app="Google Chrome" space=^3

# configure events
yabai -m signal --add event=space_changed action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=window_created action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=window_destroyed action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=window_moved action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=application_visible action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=application_hidden action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=application_launched action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=application_terminated action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=display_changed action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add event=mission_control_exit action="source ~/.config/yabai/scripts/padding.sh"

echo "yabai configuration loaded.."

