#!/usr/bin/env sh

yabai -m signal --add label="reload-sa" event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# default layout (can be bsp, stack or float)
yabai -m config layout bsp
yabai -m config external_bar all:24:0
yabai -m config auto_balance off

# Set all padding (default: 0)
# yabai -m config top_padding 2
# yabai -m config bottom_padding 2
# yabai -m config left_padding 2
# yabai -m config right_padding 2
# yabai -m config window_gap 1

# modify window shadows (default: on, options: on, off, float)
yabai -m config window_shadow off
yabai -m config window_zoom_persist on
yabai -m config window_animation_duration 0.09
yabai -m config window_animation_easing ease_out_expo
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.05
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.87
# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# center mouse on window with focus
yabai -m config mouse_follows_focus off
# focus window under cursor
yabai -m config focus_follows_mouse off
# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action stack

# disable specific apps
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Archive Utility" app="^Archive Utility$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Calendar" app="^Calendar$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="iStat Menus" app="^iStat Menus$" manage=off
yabai -m rule --add label="Little Snitch Software Update" app="^Little Snitch Software Update$" manage=off
yabai -m rule --add label="NewMail" app="^Mail$" title="New Message" manage=off
yabai -m rule --add label="Raycast" app="^Raycast" manage=off
yabai -m rule --add label="SF Symbols" app="^SF\ Symbols$" manage=off
yabai -m rule --add label="SteerMouse" app="^SteerMouse$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
yabai -m rule --add label="VLC" app="^VLC$" manage=off
yabai -m rule --add label="Weather" app="^Weather$" manage=off
yabai -m rule --add title="Open" manage=off
yabai -m rule --add label="Toggl" app="^Toggl Track$" manage=off
yabai -m rule --add label="Stream Deck" app="^Stream Deck$" manage=off

yabai -m rule --add label="Modrinth" app="^Modrinth App$" manage=off
yabai -m rule --add app="^java$" manage=off

# configure spaces
yabai -m space 1 --label "com"
yabai -m rule --add label="Mail" app="Mail" space=^com
yabai -m rule --add label="Telegram" app="Telegram" space=^com

yabai -m space 2 --label "copium"
yabai -m rule --add label="Fork" app="Fork" space=^copium
yabai -m rule --add label="Obsidian" app="Obsidian" scratchpad=obsidian

yabai -m space 3 --label "web"
yabai -m rule --add label="Safari" app="Safari" space=^web
yabai -m rule --add label="Brave" app="Brave" space=^web
yabai -m rule --add label="Google Chrome" app="Google Chrome" space=^web

# configure events
yabai -m signal --add label="padding01" event=space_changed action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding02" event=window_created action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding03" event=window_destroyed action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding04" event=window_moved action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding05" event=application_visible action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding06" event=application_hidden action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding07" event=application_launched action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding08" event=application_terminated action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding09" event=display_changed action="source ~/.config/yabai/scripts/padding.sh"
yabai -m signal --add label="padding10" event=mission_control_exit action="source ~/.config/yabai/scripts/padding.sh"

yabai -m signal --add label="autofloat" event=window_created action="yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er '.\"can-resize\" == false and .\"is-floating\" == false' && yabai -m window $YABAI_WINDOW_ID --toggle float"

echo "yabai configuration loaded.."
