[keyboard]
bindings = [
  { key = "l", mods = "Option", chars = "@" },        # restore keybinds after option_as_alt = "Both"
  { key = "e", mods = "Option", chars = "€" },        # restore keybinds after option_as_alt = "Both"
  { key = "7", mods = "Option", chars = "|" },        # restore keybinds after option_as_alt = "Both"
  { key = "7", mods = "Option|Shift", chars = "\\" }, # restore keybinds after option_as_alt = "Both"
  { key = "5", mods = "Option", chars = "[" },        # restore keybinds after option_as_alt = "Both"
  { key = "6", mods = "Option", chars = "]" },        # restore keybinds after option_as_alt = "Both"
  { key = "8", mods = "Option", chars = "{" },        # restore keybinds after option_as_alt = "Both"
  { key = "9", mods = "Option", chars = "}" },        # restore keybinds after option_as_alt = "Both"
]
