name: Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
          flavor: |
            latest=${{ github.ref_name == 'main' }}

      - name: Generate Docker metadata
        id: meta-slim
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ github.repository }}-slim
          tags: |
            type=ref,event=branch
            type=sha
          flavor: |
            latest=${{ github.ref_name == 'main' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push slim flavor
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-slim.outputs.tags }}
          labels: ${{ steps.meta-slim.outputs.labels }}
          target: slim
